# Generated by Django 4.1.3 on 2022-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_user_id_alter_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('N', 'Новость'), ('P', 'Статья')], default='P', max_length=255),
        ),
    ]
