# Generated by Django 4.1.3 on 2022-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_post_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='txt',
            field=models.IntegerField(default=0),
        ),
    ]
